# Clock 配置文件

[server]
host = "0.0.0.0:9528"

[storage]
backend = "sqlite3"  # 支持: sqlite3, mysql, postgres
conn = "clock.db"

[log]
level = "info"
filepath = "clock.log"

[auth]
user = "admin"
password = "admin"
jwt_secret = "helloClock$"

[message]
size = 1000
